In [1]:
from sklearn.tree._tree import TREE_LEAF
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
import pandas as pd
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score, roc_auc_score, mean_squared_error, mean_absolute_error
import copy as copy
import importlib
import numpy as numpy
from statistics import mean
import os
import pickle
import pydotplus

import functions as func

labels_class = ["Prog1_scaled","Prog1_beste", "MfI1_beste", "beste", "beide"]
others_class = [["Prog1_beste","MfI1_beste","beste","beide"],["MfI1_beste","beste","beide","Prog1_scaled"],["Prog1_beste","beste","beide","Prog1_scaled"],["Prog1_beste","MfI1_beste","beide","Prog1_scaled"]
         ,["Prog1_beste","MfI1_beste","beste","Prog1_scaled"]]
labels_reg = ["Prog1_scaled","Prog1_beste", "MfI1_beste", "beste"]
others_reg = [["Prog1_beste","MfI1_beste","beste"],["MfI1_beste","beste","Prog1_scaled"],["Prog1_beste","beste","Prog1_scaled"],["Prog1_beste","MfI1_beste","Prog1_scaled"]]

measure_class = ["accuracy","f1","roc_auc"]
measure_reg = ["reg_accuracy","mse","mae"]

In [2]:
other_count = 0
#Scenarios 4. – 7.
for LABEL in labels_class:
    print("====================%s=============="%(LABEL))
    #Continuuos labels after normalization and scaling not suitable for accuracy
    if LABEL == "Prog1_scaled":
        other_count+=1
        continue
    for measure in measure_class:
        print("====================%s=============="%(measure))
        if LABEL == "beide" and measure != "accuracy":
            continue
        dt = DecisionTreeClassifier(random_state=42)
        #Load data
        data_raw,train_raw,test_raw,validation_raw,names,feature_names = func.load_data_bestanden_raw(LABEL,others_class[other_count][0],
                                                                         others_class[other_count][1],
                                                                         others_class[other_count][2])
        dt.fit(train_raw[:,:-1],train_raw[:,-1])
        #Results before pruning
        func.print_results_class(dt,train_raw,test_raw,validation_raw,LABEL,"vor")
        
        os.makedirs(os.path.dirname("graphs/dot/%s/REP/%s/prune_full_dt.dot"%(LABEL,measure)), exist_ok = True)
    
        tree.export_graphviz(dt, out_file='graphs/dot/%s/REP/%s/prune_full_dt.dot'%(LABEL,measure), feature_names= names[:-1],
                     filled=True, rounded=True,special_characters=True)

        os.system("dot -T png graphs/dot/%s/REP/%s/prune_full_dt.dot -o graphs/%s/REP/%s/prune_full_dt.png"%(LABEL,measure,LABEL,measure))

        num_nodes = dt.tree_.node_count
        original_tree = copy.deepcopy(dt)
        best_tree = dt
        #Prune tree
        func.rep(dt,validation_raw,measure,LABEL,feature_names)
        
        #Render best pruned tree
        os.makedirs(os.path.dirname('graphs/dot/%s/REP/%s/best_pruned.dot'%(LABEL,measure)), exist_ok = True)
        os.makedirs(os.path.dirname('graphs/%s/REP/%s/best_pruned.dot'%(LABEL,measure)), exist_ok = True)

        tree.export_graphviz(dt, out_file='graphs/dot/%s/REP/%s/best_pruned.dot'%(LABEL,measure), feature_names= names[:-1],
                        filled=True, rounded=True,special_characters=True)
        os.system("dot -T png graphs/dot/%s/REP/%s/best_pruned.dot -o graphs/%s/REP/%s/best_pruned.png"%(LABEL,measure,LABEL,measure))
        #Results after pruning
        func.print_results_class(dt,train_raw,test_raw,validation_raw,LABEL, "nach")
        #Store model permanently
        os.makedirs(os.path.dirname("pruned_models/REP/%s/%s/%s_%s.pkl"%(LABEL,measure,LABEL,measure)), exist_ok = True)
        temp_pkl_file = open("pruned_models/REP/%s/%s/%s_%s.pkl"%(LABEL,measure,LABEL,measure), "wb")
        pickle.dump(copy.deepcopy(dt), temp_pkl_file)
        temp_pkl_file.close()
    other_count += 1

====================Prog1_scaled==============
====================Prog1_beste==============
====================accuracy==============
[[83  0]
 [ 0 37]]
ACC vor Pruning Training:  1.0
AUC vor Pruning Training:  1.0
F1 vor Pruning Training:  1.0
[[60 36]
 [17 19]]
ACC vor Pruning Test:  0.5984848484848485
AUC vor Pruning Test:  0.5763888888888888
F1 vor Pruning Test:  0.4175824175824176
[[27 20]
 [ 5  5]]
ACC vor Pruning Validation:  0.5614035087719298
AUC vor Pruning Validation:  0.5372340425531915
F1 vor Pruning Validation:  0.28571428571428575
[[83  0]
 [19 18]]
ACC nach Pruning Training:  0.8416666666666667
AUC nach Pruning Training:  0.7657114946271573
F1 nach Pruning Training:  0.6545454545454547
[[79 17]
 [24 12]]
ACC nach Pruning Test:  0.6893939393939394
AUC nach Pruning Test:  0.579861111111111
F1 nach Pruning Test:  0.36923076923076925
[[39  8]
 [ 8  2]]
ACC nach Pruning Validation:  0.7192982456140351
AUC nach Pruning Validation:  0.4776595744680851
F1 nach Pruning Validat

/home/franz/miniconda3/envs/mainenv/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/franz/miniconda3/envs/mainenv/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/franz/miniconda3/envs/mainenv/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/franz/miniconda3/envs/mainenv/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


[[83 18]
 [ 7 19]]
ACC nach Pruning Training:  0.8031496062992126
AUC nach Pruning Training:  0.8295887281035796
F1 nach Pruning Training:  0.6031746031746031
[[72 21]
 [32  9]]
ACC nach Pruning Test:  0.6044776119402985
AUC nach Pruning Test:  0.5881195908733281
F1 nach Pruning Test:  0.2535211267605634
[[25 12]
 [14  6]]
ACC nach Pruning Validation:  0.543859649122807
AUC nach Pruning Validation:  0.5094594594594595
F1 nach Pruning Validation:  0.3157894736842105
====================roc_auc==============
[[101   0]
 [  1  25]]
ACC vor Pruning Training:  0.9921259842519685
AUC vor Pruning Training:  0.9998095963442498
F1 vor Pruning Training:  0.9803921568627451
[[74 19]
 [35  6]]
ACC vor Pruning Test:  0.5970149253731343
AUC vor Pruning Test:  0.4710201940729084
F1 vor Pruning Test:  0.1818181818181818
[[20 17]
 [15  5]]
ACC vor Pruning Validation:  0.43859649122807015
AUC vor Pruning Validation:  0.3952702702702703
F1 vor Pruning Validation:  0.23809523809523808
[[101   0]
 [ 11  15

In [3]:
other_count = 0
#Scenarios 1. - 3.
for LABEL in labels_reg:
    print("====================%s=============="%(LABEL))

    for measure in measure_reg:
        print("====================%s=============="%(measure))
        if measure == "reg_accuracy":
            #Continuuos labels after normalization and scaling not suitable for accuracy
            if LABEL == "Prog1_scaled":
                continue
            dt = DecisionTreeClassifier(random_state=42)
            #Load data
            data_raw,train_raw,test_raw,validation_raw,names,feature_names = func.load_data_noten_raw(LABEL,others_reg[other_count][0],
                                                                             others_reg[other_count][1],
                                                                             others_reg[other_count][2])
            dt.fit(train_raw[:,:-1],train_raw[:,-1])
            #Results before pruning
            func.print_results_class(dt,train_raw,test_raw,validation_raw,LABEL,"vor", noten=True)
            
        else:
            dt = DecisionTreeRegressor(random_state=42)
            #Load data
            data_raw,train_raw,test_raw,validation_raw,names,feature_names = func.load_data_noten_raw(LABEL,others_reg[other_count][0],
                                                                             others_reg[other_count][1],
                                                                             others_reg[other_count][2])
            dt.fit(train_raw[:,:-1],train_raw[:,-1])
            #Results before pruning
            func.print_results_reg(dt,train_raw,test_raw,validation_raw,"vor")
        
        os.makedirs(os.path.dirname("graphs/dot/%s/REP/%s/prune_full_dt.dot"%(LABEL,measure)), exist_ok = True)
    
        tree.export_graphviz(dt, out_file='graphs/dot/%s/REP/%s/prune_full_dt.dot'%(LABEL,measure), feature_names= names[:-1],
                     filled=True, rounded=True,special_characters=True)

        os.system("dot -T png graphs/dot/%s/REP/%s/prune_full_dt.dot -o graphs/%s/REP/%s/prune_full_dt.png"%(LABEL,measure,LABEL,measure))

        num_nodes = dt.tree_.node_count
        original_tree = copy.deepcopy(dt)
        best_tree = dt
        #Prune tree
        func.rep(dt,validation_raw,measure,LABEL,feature_names)
        
        #Render best pruned tree
        os.makedirs(os.path.dirname('graphs/dot/%s/REP/%s/best_pruned.dot'%(LABEL,measure)), exist_ok = True)
        os.makedirs(os.path.dirname('graphs/%s/REP/%s/best_pruned.png'%(LABEL,measure)), exist_ok = True)

        tree.export_graphviz(dt, out_file='graphs/dot/%s/REP/%s/best_pruned.dot'%(LABEL,measure), feature_names= names[:-1],
                        filled=True, rounded=True,special_characters=True)
        os.system("dot -T png graphs/dot/%s/REP/%s/best_pruned.dot -o graphs/%s/REP/%s/best_pruned.png"%(LABEL,measure,LABEL,measure))
        
        #Results after pruning
        if measure == "reg_accuracy":
            func.print_results_class(dt,train_raw,test_raw,validation_raw,LABEL, "nach",noten=True)
        else:
            func.print_results_reg(dt,train_raw,test_raw,validation_raw, "nach")
        #Store model permanently
        os.makedirs(os.path.dirname("pruned_models/REP/%s/%s/%s_%s.pkl"%(LABEL,measure,LABEL,measure)), exist_ok = True)
        temp_pkl_file = open("pruned_models/REP/%s/%s/%s_%s.pkl"%(LABEL,measure,LABEL,measure), "wb")
        pickle.dump(copy.deepcopy(dt), temp_pkl_file)
        temp_pkl_file.close()
    other_count += 1

====================Prog1_scaled==============
====================reg_accuracy==============
====================mse==============
RMSE vor Pruning Training:  2.0545200048263767e-14
MAE vor Pruning Training:  8.037286683188018e-15
RMSE vor Pruning Test:  168.21278709496772
MAE vor Pruning Test:  130.52726197482693
RMSE vor Pruning Validation:  153.4857960399924
MAE vor Pruning Validation:  130.6356631507868
RMSE nach Pruning Training:  114.37166354207848
MAE nach Pruning Training:  90.88901723664898
RMSE nach Pruning Test:  126.98547928978628
MAE nach Pruning Test:  102.10220780383358
RMSE nach Pruning Validation:  127.26413037613827
MAE nach Pruning Validation:  107.56786539335835
====================mae==============
RMSE vor Pruning Training:  2.0545200048263767e-14
MAE vor Pruning Training:  8.037286683188018e-15
RMSE vor Pruning Test:  168.21278709496772
MAE vor Pruning Test:  130.52726197482693
RMSE vor Pruning Validation:  153.4857960399924
MAE vor Pruning Validation:  130.6356

[[18  0  0  0  0  0  0  0  0  0  2]
 [ 0  0  0  0  0  0  1  0  0  0  5]
 [ 1  0  4  0  0  0  0  0  0  0  6]
 [ 0  0  0  0  0  0  0  0  0  0  9]
 [ 0  0  0  0  0  0  0  0  0  0  2]
 [ 0  0  3  0  0  0  0  0  0  0 11]
 [ 0  0  0  0  0  0  2  0  0  0 10]
 [ 0  0  0  0  0  0  0  0  0  0 13]
 [ 0  0  0  0  0  0  1  0  0  0  6]
 [ 0  0  0  0  0  0  0  0  0  0  7]
 [ 0  0  0  0  0  0  2  0  0  0 24]]
ACC nach Pruning Training:  0.3779527559055118
[[ 7  0  7  0  0  0  1  0  0  0  5]
 [ 8  0  0  0  0  0  0  0  0  0  6]
 [ 3  0  0  0  0  0  1  0  0  0  8]
 [ 0  0  1  0  0  0  0  0  0  0  8]
 [ 1  0  0  0  0  0  0  0  0  0  9]
 [ 1  0  0  0  0  0  0  0  0  0  8]
 [ 0  0  0  0  0  0  0  0  0  0  5]
 [ 0  0  0  0  0  0  0  0  0  0  7]
 [ 2  0  0  0  0  0  0  0  0  0  2]
 [ 0  0  0  0  0  0  1  0  0  0  6]
 [ 3  0  0  0  0  0  0  0  0  0 38]]
ACC nach Pruning Test:  0.32608695652173914
[[ 5  0  0  0  0  0  0  0  0  1]
 [ 2  0  0  0  0  0  0  0  0  2]
 [ 0  0  0  0  0  0  0  0  0  6]
 [ 0  0  0  0  0